---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2021-09-26T09:52:06Z
  labels:
    app: nginx-app
  name: nginx-app
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-app
  type: LoadBalancer
status:
  loadBalancer: {}


---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: 2021-09-26T09:52:06Z
  labels:
    app: nginx-app
  name: nginx-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: 2021-09-26T09:52:06Z
      labels:
        app: nginx-app
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
