
# Default label of eks zone
# labels:  
#   failure-domain.beta.kubernetes.io/region: us-east-1
#   failure-domain.beta.kubernetes.io/zone: us-east-1a
#   kubernetes.io/hostname: ip-10-10-10-10.ec2.internal...
#   kubernetes.io/os: linux
#   topology.ebs.csi.aws.com/zone: us-east-1a
#   topology.kubernetes.io/region: us-east-1
#   topology.kubernetes.io/zone: us-east-1a
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2021-09-26T09:52:06Z
  labels:
    app: nginx-app
  name: nginx-app
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-app
  type: LoadBalancer
status:
  loadBalancer: {}


---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: 2021-09-26T09:52:06Z
  labels:
    app: nginx-app
  name: nginx-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: 2021-09-26T09:52:06Z
      labels:
        app: nginx-app
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            foo: ba
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
